### ISSUE TITLE
things to come back to

### ISSUE THREAD

**Issue by jaydeluca** [jaydeluca/code-migration-tracker#1]
- [x] move variables like repo and timeframe to arguments #2 
- [x] Create makefile for linting and tests #3 
- [x] run lint and tests in CI #3 
- [x] separate logic for filtering data out of github client #3 
- [x] rework cache to use separate files for repo cache. Otherwise the repo cache file could be huge if traversing a long time frame and sticking them all in the same one. #4 
- [x] Make filtering / rule sets more "pluggable" / customizable
